- name: install nginx
  yum:
    name:
      - nginx
      - httpd-tools
    state: present

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx service

- name: create extra configure dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /etc/nginx/ssl
    - /etc/nginx/htpasswd

- name: copy ssl files
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/{{ item }}"
    mode: '0644'
  loop:
    - yingzhuo.com.conf
    - yingzhuo.com.crt
    - yingzhuo.com.key
  notify:
    - restart nginx service

- name: copy password files
  copy:
    src: "yingzhuo.com.password"
    dest: "/etc/nginx/htpasswd/yingzhuo.com.password"
    mode: '0644'
  notify:
    - restart nginx

- name: create dir for sites
  file:
    path: /data/nginx
    state: directory
    owner: root
    group: root

- name: sync homepage content
  synchronize:
    mode: push
    src: www.yingzhuo.com
    dest: /data/nginx
    archive: no
    links: no
    recursive: yes
    rsync_opts:
      - "--delete"
      - "--delete-excluded"
      - "--exclude=.DS_Store"
      - "--exclude=.idea*"
      - "--exclude=.git*"
  changed_when: no

- name: copy vhost config files
  copy:
    dest: "/etc/nginx/conf.d/{{ item }}"
    src: "vhost/{{ item }}"
    owner: root
    group: root
  with_items:
    - www.yingzhuo.com.conf

- name: startup nginx
  service:
    name: nginx
    state: started
    enabled: yes
