- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present

- name: copy primary config file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  notify:
    - restart elasticsearch

- name: copy jvm config file
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
  notify:
    - restart elasticsearch

- name: create data dir
  file:
    path: "{{ data_dir }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch

- name: create log dir
  file:
    path: "{{ log_dir }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch

- name: start elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes
